sudo rm key.json
sudo rm myteacupapp.yml

sudo cat <<EOF >> key.json
# insert key.json
EOF

sudo ls -la 
sudo gcloud auth activate-service-account \
  obyerere@turnkey-mender-271118.iam.gserviceaccount.com \
          --key-file=key.json --project=turnkey-mender-271118

sudo gcloud container clusters get-credentials  teacup-k8s	--zone us-east1-d
sudo cat <<EOF >>myteacupapp.yml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: teacup-app-server
  labels:
    app: teacup-app-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teacup-app-server
  template:
    metadata:
      labels:
        app: teacup-app-server
    spec:
      containers:
      - name: teacup-app-server
        image: obyerere1/tea-be:v0.0.1
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8086
        resources:
          limits:
            cpu: 0.2
            memory: "200Mi"
        env:
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-pass
              key: password
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: mysql-db-url
              key: url
---
apiVersion: v1
kind: Service
metadata:
  name: teacup-app-server
spec:
  type: NodePort
  selector:
    app: teacup-app-server
  ports:
      - protocol: TCP
        port: 80
        targetPort: 80
        
EOF


sudo kubectl create -f myteacupapp.yml







